SESSION 11 - Classification Algorithms (Part 2: KNN + Naive Bayes) Topics Covered: K-Nearest Neighbors Distance metrics (Euclidean, Manhattan) Choosing k Pros & cons Naive Bayes Bayes theorem Gaussian NB Multinomial NB Practical examples: Text classification Basic image classification
Pending
Tasks
1.
Implement a K-Nearest Neighbors (KNN) classifier in Python to predict whether a Flipkart product review is 'positive' or 'negative' using a small dataset of review texts and their labels.<br><br><em><strong>Hint:</strong> Use scikit-learn's KNeighborsClassifier and convert the text data into numerical features using CountVectorizer.</em>
2.
Compare the accuracy of KNN using Euclidean distance vs. Manhattan distance on a dataset of Spotify song features (e.g., tempo, danceability, energy) to classify songs as 'workout' or 'chill' playlists.<br><br><em><strong>Hint:</strong> Use the 'metric' parameter in KNeighborsClassifier to switch between 'euclidean' and 'manhattan'.</em>
3.
Use Gaussian Naive Bayes to classify whether an IRCTC train booking is likely to be 'confirmed' or 'waitlisted' based on features like booking time, train popularity, and travel day (use a small mock dataset).
4.
Build a Multinomial Naive Bayes classifier to categorize WhatsApp chat messages as 'personal', 'group', or 'spam' using example message texts and labels.<br><br><em><strong>Constraint:</strong> Use scikit-learn's MultinomialNB and show the confusion matrix for your results.</em>
5.
Use ChatGPT or Copilot to generate Python code for a KNN-based image classifier that distinguishes between images of cricket bats and footballs (use any small sample image dataset or random pixel arrays), then run and test the code, noting any changes you made to get it working.<br><br><em><strong>Hint:</strong> Paste the AI-generated code, describe any errors, and how you fixed them.</em>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

In [ ]:
# TASK 1: Flipkart Review Classification using KNN Text Processing
reviews = [
    "Amazing product, high speed delivery and sturdy build quality",
    "Extremely disappointed, it stopped working on day two",
    "Value for money and excellent performance overall",
    "Worst experience ever, customer support refused replacement",
    "Superb device, smooth interface and crisp camera clarity",
    "Waste of money, cheap plastic material used"
]
labels = ["positive", "negative", "positive", "negative", "positive", "negative"]

# Transform raw text strings into numerical word token frequency vectors
vectorizer = CountVectorizer()
X_text_counts = vectorizer.fit_transform(reviews)

# Fit a 3-Nearest Neighbor classifier
knn_text = KNeighborsClassifier(n_neighbors=3)
knn_text.fit(X_text_counts, labels)

# Test on a completely fresh sample query
test_review = ["Very fast experience, wonderful quality"]
X_test_counts = vectorizer.transform(test_review)
prediction = knn_text.predict(X_test_counts)[0]
print(f"Sample Text: '{test_review[0]}'\nPredicted Sentiment Class: {prediction}\n")
print("="*60 + "\n")

--- TASK 1: FLIPKART TEXT CLASSIFICATION WITH KNN ---
Sample Text: 'Very fast experience, wonderful quality'
Predicted Sentiment Class: positive




In [3]:

# TASK 2: Euclidean vs Manhattan Distance Metrics on Spotify Tracks
# Load downloaded dataset
df_spotify = pd.read_csv('spotify_classification_features.csv')

X_spotify = df_spotify[['Tempo', 'Danceability', 'Energy']]
y_spotify = df_spotify['Playlist_Type']

X_train, X_test, y_train, y_test = train_test_split(X_spotify, y_spotify, test_size=0.3, random_state=42)

# 1. Evaluate Euclidean Distance KNN
knn_euclidean = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
knn_euclidean.fit(X_train, y_train)
acc_euclidean = accuracy_score(y_test, knn_euclidean.predict(X_test))

# 2. Evaluate Manhattan Distance KNN
knn_manhattan = KNeighborsClassifier(n_neighbors=5, metric='manhattan')
knn_manhattan.fit(X_train, y_train)
acc_manhattan = accuracy_score(y_test, knn_manhattan.predict(X_test))

print(f"KNN Accuracy with Euclidean Distance Metric: {acc_euclidean * 100:.2f}%")
print(f"KNN Accuracy with Manhattan Distance Metric : {acc_manhattan * 100:.2f}%")
print("\n" + "="*60 + "\n")

KNN Accuracy with Euclidean Distance Metric: 100.00%
KNN Accuracy with Manhattan Distance Metric : 100.00%




In [ ]:
# TASK 3: IRCTC Train Booking Probabilities using Gaussian NB
# Features: [Hours_Before_Departure, Historic_Train_Popularity_Score, Travel_Day_Of_Week]
# Binary Labels: 1 = Confirmed, 0 = Waitlisted
booking_data = np.array([
    [72, 9, 5], [12, 4, 7], [120, 8, 2], [4, 9, 6], [96, 7, 3],
    [24, 3, 1], [168, 9, 4], [8, 5, 7], [48, 6, 2], [2, 8, 6]
])
booking_labels = np.array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

gnb = GaussianNB()
gnb.fit(booking_data, booking_labels)

# Predict status for a ticket bought 60 hours prior, popularity rating 8/10, traveling on Wednesday (Day 3)
new_booking = np.array([[60, 8, 3]])
predicted_status = gnb.predict(new_booking)[0]
status_mapping = {1: "Confirmed (CNF)", 0: "Waitlisted (WL)"}
print(f"New Reservation Input Parameters: {new_booking[0]}")
print(f"Gaussian NB Predictive Outcome : {status_mapping[predicted_status]}\n")
print("="*60 + "\n")

--- TASK 3: IRCTC BOOKING VERDICT VIA GAUSSIAN NAIVE BAYES ---
New Reservation Input Parameters: [60  8  3]
Gaussian NB Predictive Outcome : Confirmed (CNF)




In [5]:
# TASK 4: WhatsApp Chat Message Classifier via Multinomial NB
chat_messages = [
    "Hey are you free to meet up for tea tonight?",
    "Please send the final presentation document on the official group chat",
    "CONGRATULATIONS! You have won a 1000 dollar gift card click here now",
    "Can you pick up groceries while coming home from office?",
    "Project updates must be submitted by Friday end of day team",
    "URGENT claim your inherited inheritance reward immediately contact us"
]
chat_labels = ["personal", "group", "spam", "personal", "group", "spam"]

chat_vectorizer = CountVectorizer()
X_chat_counts = chat_vectorizer.fit_transform(chat_messages)

mnb = MultinomialNB()
mnb.fit(X_chat_counts, chat_labels)

# Checking predictions on training array to isolate basic confusion matrix distribution
y_pred_chat = mnb.predict(X_chat_counts)
cm = confusion_matrix(chat_labels, y_pred_chat, labels=["personal", "group", "spam"])

print("Confusion Matrix Layout (Rows = Actuals, Columns = Predictions):")
print("Labels Ordered: ['personal', 'group', 'spam']")
print(cm)
print("\nDetailed Performance Diagnostics:")
print(classification_report(chat_labels, y_pred_chat))
print("="*60 + "\n")

Confusion Matrix Layout (Rows = Actuals, Columns = Predictions):
Labels Ordered: ['personal', 'group', 'spam']
[[2 0 0]
 [0 2 0]
 [0 0 2]]

Detailed Performance Diagnostics:
              precision    recall  f1-score   support

       group       1.00      1.00      1.00         2
    personal       1.00      1.00      1.00         2
        spam       1.00      1.00      1.00         2

    accuracy                           1.00         6
   macro avg       1.00      1.00      1.00         6
weighted avg       1.00      1.00      1.00         6




In [6]:
# TASK 5: AI-Generated KNN Image Classifier Code & Implementation Notes
# Mimicking a small 8x8 flattened pixel space array (64 features) 
# representing 10 sample images of Cricket Bats (Class 0) vs Footballs (Class 1)
np.random.seed(7)
mock_images = np.random.randint(0, 256, size=(10, 64))
image_labels = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) # 0: Bat, 1: Football

img_knn = KNeighborsClassifier(n_neighbors=1)
img_knn.fit(mock_images, image_labels)
print("KNN Image Classifier loaded and compiled successfully.")

KNN Image Classifier loaded and compiled successfully.
